#!/usr/bin/env ruby

x = ARGV[0].to_i
file = ARGV[1]

top_xs = []

File.readlines(file).each do |line|
    num = line.to_i
    break if num == nil

    add_to_xs = top_xs.length < x || num > top_xs.last

    if add_to_xs
        top_xs = (top_xs << num).sort().reverse()[0..x-1]
    end
end

puts top_xs
