#!/usr/bin/env ruby

x = ARGV[0].to_i
file = ARGV[1]

top_xs = []

def debug(msg)
    puts ">>> #{msg}"
end

File.readlines(file).each do |line|
    num = line.to_i

    add_to_xs = false
    top_xs.each do |topx|
        debug "#{num}, #{topx}"
        if num > topx
            debug "adding"
            add_to_xs = true
        end
    end

    if add_to_xs || top_xs.length < x
        top_xs << num
        top_xs = top_xs.sort().reverse()[0..x-1]
    end
end

puts top_xs
